<script type="text/javascript">
  function produce_department(){
    var College = document.getElementById("Course_College").value;
    document.getElementById("Course_Department").length=0;
    var x = document.getElementById("Course_Department");

if (College=='理工學院'){
var option=document.createElement("option");
option.text = " 應用數學系暨研究所";
option.value = "應用數學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 電子物理學系光電暨固態電子研究所";
option.value = "電子物理學系光電暨固態電子研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 應用化學系暨研究所";
option.value = "應用化學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 資訊工程學系暨研究所";
option.value = "資訊工程學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 生物機電工程學系暨研究所";
option.value = "生物機電工程學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 土木與水資源工程學系暨研究所";
option.value = "土木與水資源工程學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 電機工程學系暨研究所";
option.value = "電機工程學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 機械與能源工程學系";
option.value = "機械與能源工程學系";
x.add(option);
}
if (College=='師範學院'){
var option=document.createElement("option");
option.text = " 教育學系暨研究所";
option.value = "教育學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 輔導與諮商學系暨研究所";
option.value = "輔導與諮商學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 體育與健康休閒學系暨研究所";
option.value = "體育與健康休閒學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 特殊教育學系暨研究所";
option.value = "特殊教育學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 幼兒教育學系暨研究所";
option.value = "幼兒教育學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 教育行政與政策發展研究所";
option.value = "教育行政與政策發展研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 數理教育研究所";
option.value = "數理教育研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 數位學習設計與管理學系暨研究所";
option.value = "數位學習設計與管理學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 教學專業國際碩士學位學程";
option.value = "教學專業國際碩士學位學程";
x.add(option);
}
if (College=='人文藝術學院'){
var option=document.createElement("option");
option.text = " 中國文學系暨研究所";
option.value = "中國文學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 視覺藝術學系暨研究所";
option.value = "視覺藝術學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 應用歷史學系暨研究所";
option.value = "應用歷史學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 外國語言學系暨研究所";
option.value = "外國語言學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 音樂學系暨研究所";
option.value = "音樂學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 人文藝術中心";
option.value = "人文藝術中心";
x.add(option);
var option=document.createElement("option");
option.text = " 台灣文化研究中心";
option.value = "台灣文化研究中心";
x.add(option);
}
if (College=='管理學院'){
var option=document.createElement("option");
option.text = " 企業管理學系暨研究所";
option.value = "企業管理學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 應用經濟學系暨研究所";
option.value = "應用經濟學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 生物事業管理學系暨研究所";
option.value = "生物事業管理學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 資訊管理學系暨研究所";
option.value = "資訊管理學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 財務金融學系";
option.value = "財務金融學系";
x.add(option);
var option=document.createElement("option");
option.text = " 行銷與觀光管理學系暨研究所";
option.value = "行銷與觀光管理學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 管院碩士在職專班";
option.value = "管院碩士在職專班";
x.add(option);
var option=document.createElement("option");
option.text = " 全英文授課觀光暨管理碩士學位學程";
option.value = "全英文授課觀光暨管理碩士學位學程";
x.add(option);
var option=document.createElement("option");
option.text = " 電子商務研究中心";
option.value = "電子商務研究中心";
x.add(option);
var option=document.createElement("option");
option.text = " 農企業經營管理研究中心";
option.value = "農企業經營管理研究中心";
x.add(option);
}
if (College=='農學院'){
var option=document.createElement("option");
option.text = " 農藝學系暨研究所";
option.value = "農藝學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 園藝學系暨研究所";
option.value = "園藝學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 森林暨自然資源學系暨研究所";
option.value = "森林暨自然資源學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 木質材料與設計學系暨研究所";
option.value = "木質材料與設計學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 動物科學系暨研究所";
option.value = "動物科學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 生物農業科技學系";
option.value = "生物農業科技學系";
x.add(option);
var option=document.createElement("option");
option.text = " 景觀學系";
option.value = "景觀學系";
x.add(option);
var option=document.createElement("option");
option.text = " 農業科學博士學位學程";
option.value = "農業科學博士學位學程";
x.add(option);
var option=document.createElement("option");
option.text = " 植物醫學系";
option.value = "植物醫學系";
x.add(option);
var option=document.createElement("option");
option.text = " 農學院農業科技全英碩士學位學程";
option.value = "農學院農業科技全英碩士學位學程";
x.add(option);
var option=document.createElement("option");
option.text = " 生物技術學程";
option.value = "生物技術學";
x.add(option);
var option=document.createElement("option");
option.text = " 蘭花生技學程";
option.value = "蘭花生技學程";
x.add(option);
var option=document.createElement("option");
option.text = " 有機農業學程";
option.value = "有機農業學程";
x.add(option);
var option=document.createElement("option");
option.text = " 農場管理進修學士學位學程";
option.value = "農場管理進修學士學位學程";
x.add(option);
}
if (College=='生命科學院'){
var option=document.createElement("option");
option.text = " 食品科學系暨研究所";
option.value = "食品科學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 水生生物科學系暨研究所";
option.value = "水生生物科學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 生物資源學系暨研究所";
option.value = "生物資源學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 生化科技學系暨研究所";
option.value = "生化科技學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 微生物免疫與生物藥學系暨研究所";
option.value = "微生物免疫與生物藥學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 檢驗分析及技術推廣服務中心";
option.value = "檢驗分析及技術推廣服務中心";
x.add(option);
var option=document.createElement("option");
option.text = " 生命科學全英文碩士學位學程";
option.value = "生命科學全英文碩士學位學程";
x.add(option);
}
if (College=='獸醫學院'){
var option=document.createElement("option");
option.text = " 獸醫學系暨研究所";
option.value = "獸醫學系暨研究所";
x.add(option);
var option=document.createElement("option");
option.text = " 雲嘉南動物疾病診斷中心";
option.value = "雲嘉南動物疾病診斷中心";
x.add(option);
var option=document.createElement("option");
option.text = " 獸醫學院附設動物醫院";
option.value = "獸醫學院附設動物醫院";
x.add(option);
  }
 } 
</script>